// =============================================================================
// COREicons — Heroicons Outline Re-exports
// All 150+ HiOutline icons from solid-icons/hi, organized by category.
// Import from "@core-suite/icons" or "@core-suite/icons/heroicons".
// Copyright (c) 2024-2026 CORE Project Contributors
// Licensed under MIT License
// =============================================================================

export {
  // Navigation & Actions
  HiOutlineArrowLeft,
  HiOutlineArrowRight,
  HiOutlineArrowUp,
  HiOutlineArrowDown,
  HiOutlineArrowPath,
  HiOutlineArrowUturnLeft,
  HiOutlineArrowUturnRight,
  HiOutlineArrowTopRightOnSquare,
  HiOutlineArrowDownTray,
  HiOutlineArrowUpTray,
  HiOutlineArrowRightOnRectangle,

  // Files & Folders
  HiOutlineFolder,
  HiOutlineFolderOpen,
  HiOutlineFolderPlus,
  HiOutlineFolderMinus,
  HiOutlineFolderArrowDown,
  HiOutlineDocument,
  HiOutlineDocumentText,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentArrowDown,
  HiOutlineDocumentArrowUp,
  HiOutlineDocumentMagnifyingGlass,
  HiOutlineDocumentCheck,
  HiOutlineDocumentPlus,
  HiOutlineDocumentMinus,
  HiOutlineArchiveBox,
  HiOutlineArchiveBoxArrowDown,
  HiOutlineClipboard,
  HiOutlineClipboardDocument,
  HiOutlineClipboardDocumentList,
  HiOutlineClipboardDocumentCheck,
  HiOutlineInbox,

  // UI Controls
  HiOutlineChevronDown,
  HiOutlineChevronUp,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronDoubleDown,
  HiOutlineChevronDoubleUp,
  HiOutlineChevronDoubleLeft,
  HiOutlineChevronDoubleRight,
  HiOutlineBars3,
  HiOutlineBars4,
  HiOutlineBars3BottomLeft,
  HiOutlineBars3BottomRight,
  HiOutlineEllipsisHorizontal,
  HiOutlineEllipsisVertical,
  HiOutlineXMark,
  HiOutlinePlus,
  HiOutlineMinus,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineCheckBadge,
  HiOutlineXCircle,
  HiOutlinePlusCircle,
  HiOutlineMinusCircle,

  // Search & View
  HiOutlineMagnifyingGlass,
  HiOutlineMagnifyingGlassPlus,
  HiOutlineMagnifyingGlassMinus,
  HiOutlineMagnifyingGlassCircle,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineFunnel,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineAdjustmentsVertical,
  HiOutlineViewColumns,
  HiOutlineSquares2x2,
  HiOutlineListBullet,
  HiOutlineTableCells,
  HiOutlineChartBar,
  HiOutlineChartPie,
  HiOutlineChartBarSquare,
  HiOutlineArrowsRightLeft,

  // Status & Alerts
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineInformationCircle,
  HiOutlineQuestionMarkCircle,
  HiOutlineBellAlert,
  HiOutlineBell,
  HiOutlineShieldCheck,
  HiOutlineShieldExclamation,

  // Data & Database
  HiOutlineCircleStack,
  HiOutlineServerStack,
  HiOutlineServer,
  HiOutlineCpuChip,
  HiOutlineCommandLine,
  HiOutlineCodeBracket,
  HiOutlineCodeBracketSquare,
  HiOutlineFingerPrint,
  HiOutlineKey,
  HiOutlineLockClosed,
  HiOutlineLockOpen,

  // Media & Content
  HiOutlinePhoto,
  HiOutlineFilm,
  HiOutlineMusicalNote,
  HiOutlineVideoCamera,
  HiOutlineCamera,
  HiOutlineMicrophone,
  HiOutlineSpeakerWave,
  HiOutlineSpeakerXMark,

  // Communication
  HiOutlineEnvelope,
  HiOutlineEnvelopeOpen,
  HiOutlineChatBubbleLeft,
  HiOutlineChatBubbleLeftRight,
  HiOutlineChatBubbleBottomCenter,
  HiOutlineChatBubbleBottomCenterText,
  HiOutlineChatBubbleOvalLeft,
  HiOutlinePhone,

  // Time & Calendar
  HiOutlineClock,
  HiOutlineCalendar,
  HiOutlineCalendarDays,

  // Business
  HiOutlineBriefcase,

  // Settings & Tools
  HiOutlineCog6Tooth,
  HiOutlineCog8Tooth,
  HiOutlineWrench,
  HiOutlineWrenchScrewdriver,
  HiOutlinePaintBrush,
  HiOutlineSparkles,
  HiOutlineBolt,
  HiOutlineFire,
  HiOutlineBeaker,

  // Devices
  HiOutlineDevicePhoneMobile,
  HiOutlineDeviceTablet,
  HiOutlineComputerDesktop,
  HiOutlineTv,
  HiOutlinePrinter,
  HiOutlineWifi,
  HiOutlineSignal,

  // Storage
  HiOutlineCloudArrowDown,
  HiOutlineCloudArrowUp,
  HiOutlineCloud,

  // People & Users
  HiOutlineUser,
  HiOutlineUserCircle,
  HiOutlineUserGroup,
  HiOutlineUserPlus,
  HiOutlineUserMinus,
  HiOutlineUsers,

  // Misc
  HiOutlineHome,
  HiOutlineStar,
  HiOutlineHeart,
  HiOutlineBookmark,
  HiOutlineFlag,
  HiOutlineTag,
  HiOutlineHashtag,
  HiOutlineAtSymbol,
  HiOutlineLink,
  HiOutlinePaperClip,
  HiOutlineTrash,
  HiOutlinePencil,
  HiOutlinePencilSquare,
  HiOutlineSquare2Stack,
  HiOutlineArrowsPointingOut,
  HiOutlineArrowsPointingIn,
  HiOutlineQueueList,
  HiOutlineRectangleStack,
  HiOutlineRectangleGroup,
  HiOutlineCube,
  HiOutlineCubeTransparent,
  HiOutlineGlobeAlt,
  HiOutlineMap,
  HiOutlineMapPin,
  HiOutlineBuildingOffice,
  HiOutlineBuildingOffice2,
  HiOutlineCalculator,
  HiOutlineCurrencyDollar,
  HiOutlineScale,
  HiOutlineHandThumbUp,
  HiOutlineHandThumbDown,
  HiOutlinePlayCircle,
  HiOutlinePauseCircle,
  HiOutlineStopCircle,
  HiOutlinePlay,
  HiOutlinePause,
  HiOutlineStop,
  HiOutlineForward,
  HiOutlineBackward,
  HiOutlineSun,
  HiOutlineMoon,
  HiOutlineAcademicCap,
} from "solid-icons/hi";
